/-
Copyright (c) Meta Platforms, Inc. and affiliates.
All rights reserved.

This source code is licensed under the license found in the
LICENSE file in the root directory of this source tree.
-/

import Code.FrontierA.TriangularIsingTorusCycleHolonomy

namespace StatMech.FrontierA

#print axioms triangularTorusTurnRoot_pow_eight
#print axioms triangularKacWardTurnMatrix_eq_zpow
#print axioms prod_triangularKacWardTurnMatrix_eq_zpow_sum
#print axioms triangularTorusTurnRoot_zpow_even_revolutions
#print axioms triangularTorusTurnRoot_zpow_odd_revolutions
#print axioms prod_triangularKacWardTurnMatrix_eq_one_of_even_revolutions
#print axioms prod_triangularKacWardTurnMatrix_eq_neg_one_of_odd_revolutions
#print axioms triangular_open_intersection_edge_eq
#print axioms triangularTorusGraphPhase_one_one_apply
#print axioms triangularTorus_cycleDirection_nonbacktracking
#print axioms triangularTorus_cyclePhaseProduct_eq_turnProduct
#print axioms triangularTorus_cyclePhaseProduct_eq_one_of_even_revolutions
#print axioms triangularTorus_cyclePhaseProduct_eq_neg_one_of_odd_revolutions
#print axioms triangularTorusTurnExponent_cast_eq_angleClass_sub
#print axioms exists_triangularTorusTurnExponent_sum_eq_eight_mul
#print axioms exists_triangularTorus_cycleTurnSum_eq_eight_mul

end StatMech.FrontierA
