/-
Copyright (c) Meta Platforms, Inc. and affiliates.
All rights reserved.

This source code is licensed under the license found in the
LICENSE file in the root directory of this source tree.
-/

import Code.FK.PeriodicPlanarSheffieldCommonArray

open StatMech.FK.PeriodicPlanar

set_option linter.style.longLine false

#print axioms boundaryGridWidth_pos
#print axioms boundaryGridHeight_pos
#print axioms boundaryGrid_left_aligned
#print axioms boundaryGrid_bottom_aligned
#print axioms boundaryGrid_right_aligned
#print axioms boundaryGrid_top_aligned
#print axioms boundaryGrid_bottom_row_aligned
#print axioms boundaryGrid_left_column_aligned
#print axioms boundaryGrid_right_column_aligned
#print axioms boundaryGrid_top_row_aligned
#print axioms StatMech.FK.PeriodicPlanar.PeriodicPlaneEmbedding.rectBottomConnection_boundaryGrid_measureReal_le
#print axioms StatMech.FK.PeriodicPlanar.PeriodicPlaneEmbedding.rectLeftConnection_boundaryGrid_measureReal_le
#print axioms StatMech.FK.PeriodicPlanar.PeriodicPlaneEmbedding.rectRightConnection_boundaryGrid_measureReal_le
#print axioms StatMech.FK.PeriodicPlanar.PeriodicPlaneEmbedding.rectTopConnection_boundaryGrid_measureReal_le
#print axioms StatMech.FK.PeriodicPlanar.PeriodicPlaneEmbedding.preferenceGrid_translatedSet_subset_rect_of_commonSquare
#print axioms StatMech.FK.PeriodicPlanar.PeriodicPlaneEmbedding.preferenceGrid_translatedSet_subset_rect_of_corners
#print axioms exists_deep_common_preference_grid_witness
#print axioms StatMech.FK.PeriodicPlanar.PeriodicPlaneEmbedding.exists_uniformRadius_deepGridPreference_crossing_max_tendsto_one
#print axioms exists_commonPreferenceExtents_ge
#print axioms exists_commonPositivePreferenceExtents
