/-
Copyright (c) Meta Platforms, Inc. and affiliates.
All rights reserved.

This source code is licensed under the license found in the
LICENSE file in the root directory of this source tree.
-/

import Code.FK.PeriodicPlanarSheffieldPairedRecurrence

open StatMech.FK.PeriodicPlanar

#print axioms exists_pairedCommonBoundaryPairMergeRadius
#print axioms exists_pairedMixedBoundaryScores_atExtents
#print axioms exists_alignedExactExtentPairedMixedBoundaryScores_atExtents
#print axioms exists_pairedAlignedConnectorSlack
#print axioms AlignedExactExtentPairedMixedBoundaryScores.primalConnector_subset_narrow
#print axioms AlignedExactExtentPairedMixedBoundaryScores.dualConnector_subset_narrow
#print axioms AlignedExactExtentPairedMixedBoundaryScores.primalConnector_subset_wide
#print axioms AlignedExactExtentPairedMixedBoundaryScores.dualConnector_subset_wide
#print axioms ExactExtentPairedMixedBoundaryScores.enlargeWideRight
#print axioms ExactExtentPairedMixedBoundaryScores.enlargeWide
#print axioms ExactExtentPairedMixedBoundaryScores.primalConnector_subset_narrow
#print axioms ExactExtentPairedMixedBoundaryScores.dualConnector_subset_narrow
#print axioms ExactExtentPairedMixedBoundaryScores.primalConnector_subset_wide
#print axioms ExactExtentPairedMixedBoundaryScores.dualConnector_subset_wide
#print axioms exists_exactExtentPairedMixedBoundaryScores_thresholds
#print axioms ExactExtentPairedMixedBoundaryScores.extentX_le_wideSpan
#print axioms ExactExtentPairedMixedBoundaryScores.dualVerticalMerge_translate_measureReal_le
#print axioms ExactExtentPairedMixedBoundaryScores.dualHorizontalMerge_translate_measureReal_le
#print axioms ExactExtentPairedMixedBoundaryScores.dualVerticalCrossing_ge_translate_inactive
#print axioms ExactExtentPairedMixedBoundaryScores.dualHorizontalCrossing_ge_translate_inactive
#print axioms dualVerticalCrossing_translate_inactive_tendsto_one
#print axioms dualHorizontalCrossing_translate_inactive_tendsto_one
#print axioms AlignedExactExtentPairedMixedBoundaryScores.wideSpan_formula
#print axioms AlignedExactExtentPairedMixedBoundaryScores.dualLeftSource_transport
#print axioms AlignedExactExtentPairedMixedBoundaryScores.dualRightSource_transport
#print axioms AlignedExactExtentPairedMixedBoundaryScores.dualBottomSource_transport
#print axioms AlignedExactExtentPairedMixedBoundaryScores.dualTopSource_transport
#print axioms AlignedExactExtentPairedMixedBoundaryScores.dualVerticalMerge_transport_measureReal_le
#print axioms AlignedExactExtentPairedMixedBoundaryScores.dualHorizontalMerge_transport_measureReal_le
#print axioms nonempty_alignedNormalRotatedInsetPairedMixedBoundaryScores
#print axioms nonempty_alignedNormalTwoRotatedEndpointPairedMixedBoundaryScores
#print axioms PeriodicPlaneEmbedding.horizontalCrossing_translate_measureReal_le
#print axioms PeriodicPlaneEmbedding.verticalCrossing_translate_measureReal_le
#print axioms PeriodicPlaneEmbedding.horizontalCrossing_translate_tendsto_one
#print axioms PeriodicPlaneEmbedding.verticalCrossing_translate_tendsto_one
#print axioms PeriodicPlaneEmbedding.crossingMax_independent_translate_tendsto_one
#print axioms exists_matched_commonSquareNormalBoundaryBandData_ge
#print axioms PeriodicPlaneEmbedding.exists_commonSquareNormalBoundaryBands_outward
#print axioms PeriodicPlaneEmbedding.exists_pointwise_commonSquareNormalBoundaryBands_outward
#print axioms nonempty_alignedCrossNestedThreePairedMixedBoundaryScores
#print axioms exists_alignedCrossNestedThreePairedMixedBoundaryScores_ge
#print axioms nonempty_alignedRotatedCrossNestedThreePairedMixedBoundaryScores
#print axioms exists_alignedCrossNestedPairedSequence_with_primalAdjacent
#print axioms exists_alignedCrossNestedPairedSequence_with_primalAdjacent_ge
#print axioms AlignedCrossNestedPairedSequence.primalAdjacent_transitionCoordinates
#print axioms AlignedCrossNestedPairedSequence.primalAdjacent_translatedTransitionCoordinates
#print axioms AlignedCrossNestedPairedSequence.endpoint_transitionCoordinates_of_mergeLimits
#print axioms
  AlignedCrossNestedPairedSequence.dual_endpoint_transitionCoordinates_of_mergeLimits
#print axioms
  AlignedCrossNestedPairedSequence.exists_endpoint_transitionCoordinates_of_connectorContainment
#print axioms
  AlignedCrossNestedPairedSequence.exists_dual_endpoint_transitionCoordinates_of_connectorContainment
#print axioms AlignedCrossNestedPairedSequence.transitionCoordinates_spans
#print axioms
  AlignedCrossNestedPairedSequence.transitionCoordinates_spans_of_current_gt
#print axioms AlignedCrossNestedPairedSequence.translatedTransitionCoordinates_spans
#print axioms nonempty_crossNestedThreePairedMixedBoundaryScores
#print axioms exists_exactExtentPairedMixedBoundaryScores_ge
#print axioms nonempty_pairedAlignedMixedLevelStep
#print axioms exists_recursivePairedAlignedMixedLevelSteps
#print axioms exists_recursivePairedAlignedMixedLevelSteps_with_limits
#print axioms exists_cofinalIndex_five_uniform_tendsto_one_below_diagonal
#print axioms PeriodicPlanarDualPair.PointwiseRecursiveRectangleArrayCertificate.toRecursive
#print axioms PeriodicPlanarDualPair.PointwiseRecursiveRectangleArrayCertificate.false
#print axioms PeriodicPlanarDualPair.pointwiseRecursiveRectangleArray_false_of_normal_rotated_limits
#print axioms PeriodicPlanarDualPair.freeBufferedInfiniteVolume_commonUnique_measure_ne_one_of_normal_rotated_limits
#print axioms PeriodicPlanarDualPair.dualMeasure_crossingMax_tendsto_one
#print axioms PeriodicPlanarDualPair.dualMeasure_twoLevel_outward_limits
#print axioms PeriodicPlanarDualPair.variablePadTwoLevel_false_of_normal_rotated_limits
#print axioms PeriodicPlanarDualPair.freeBufferedInfiniteVolume_commonUnique_measure_ne_one_of_variablePad_normal_rotated_limits
#print axioms PeriodicPlanarDualPair.variablePadTwoLevel_false_of_pointwise_limits
#print axioms PeriodicPlanarDualPair.variablePadTwoLevel_false_of_pointwise_transitions
#print axioms PeriodicPlanarDualPair.freeBufferedInfiniteVolume_commonUnique_measure_ne_one_of_pointwise_transitions
#print axioms PeriodicPlanarDualPair.freeBufferedInfiniteVolume_commonUnique_measure_ne_one_of_pointwise_variablePad_limits
#print axioms PeriodicPlanarDualPair.ComplementaryCrossNestedLimitCertificate.false
#print axioms branchAlignedComplementaryLimits_false
#print axioms
  PeriodicPlanarDualPair.variablePadBranchAlignedComplementary_false
#print axioms
  PeriodicPlanarDualPair.outwardBranchAlignedComplementary_false
#print axioms
  PeriodicPlanarDualPair.variablePadComplementaryCrossNested_false
#print axioms
  AlignedCrossNestedPairedSequence.false_of_primalAdjacent_and_dualMergeLimits
#print axioms
  AlignedCrossNestedPairedSequence.exists_mixedEndpointRadii_false_of_primalAdjacent
#print axioms
  PeriodicPlanarDualPair.variablePadComplementaryEndpoints_false
#print axioms
  PeriodicPlaneEmbedding.exists_deep_adjacentHeight_preference_crossing_branch
#print axioms
  PeriodicPlaneEmbedding.exists_uniformTemplate_deepGrid_adjacentHeight_crossing_max_tendsto_one
#print axioms
  PeriodicPlaneEmbedding.exists_adjacentHeight_pairMergeRadius_at_error
#print axioms exists_radiusFirst_adjacentEndpointRow
#print axioms exists_radiusFirst_dependentGeometry_adjacentEndpointRow
#print axioms nonempty_radiusFirstAdjacentEndpointRow
#print axioms exists_recursiveRadiusFirstAdjacentEndpointRows_with_limits
#print axioms
  PeriodicPlaneEmbedding.exists_uniformTemplateAdjacentBoundaryBandCrossingRadius
#print axioms
  PeriodicPlaneEmbedding.exists_uniformTemplateAdjacentBoundaryBandCrossingRadius_with_pairMerge
#print axioms
  PeriodicPlaneEmbedding.exists_uniformAdjacentBoundaryBandRadius_with_cofinalConnectorSchedule
#print axioms
  PeriodicPlaneEmbedding.exists_uniformOutwardBoundaryCrossingRadius
#print axioms exists_pairedAdjacentBoundaryBandScheduleData
#print axioms PeriodicPlanarDualPair.exists_canonicalPairedAdjacentBoundaryBandScheduleData_of_common
#print axioms exists_pairedAdjacentOutwardScheduleData
#print axioms PeriodicPlanarDualPair.exists_canonicalPairedAdjacentOutwardScheduleData_of_common
#print axioms DualOutwardBoundaryBandLevel.crossing_limit
#print axioms PairedBoundaryBandLevel.primalAdjacent_limit
#print axioms PairedBoundaryBandLevel.dual_limit
#print axioms PairedAdjacentBoundaryBandTransition.local_limits
#print axioms
  PairedAdjacentBoundaryBandTransition.false_of_endpoints_and_matched
#print axioms
  PeriodicPlanarDualPair.PaddedPairedAdjacentTransition.false
#print axioms
  PeriodicPlaneEmbedding.deepPreferenceGrid_orbitBox_subset_rect
#print axioms
  PeriodicPlaneEmbedding.exists_coupled_endpointCrossings_tendsto_one_of_unique
#print axioms
  PeriodicPlaneEmbedding.exists_dependentSpan_endpointCrossings_tendsto_one_of_unique
#print axioms
  PeriodicPlaneEmbedding.exists_rowwise_dependentSpan_endpointCrossings_tendsto_one_of_unique
#print axioms nonempty_dependentRadiusFirstAdjacentEndpointRow
#print axioms
  exists_recursiveDependentRadiusFirstAdjacentEndpointRows_with_limits
#print axioms exists_carriedAsymmetricEndpointCoordinates_with_limits
#print axioms
  PeriodicPlanarDualPair.exists_carriedAsymmetricEndpoints_false_of_primal_limit
#print axioms
  PeriodicPlaneEmbedding.exists_uniformOrbitBoxMixedRadius_alignedExact_primalLimit
#print axioms PeriodicPlaneEmbedding.CarriedCrossNestedArray.reframe
#print axioms
  PeriodicPlaneEmbedding.CarriedCrossNestedArray.reframeByCoordinateBounds
#print axioms PeriodicPlanarDualPair.horizontalDualVerticalEndpoint_false
#print axioms PeriodicPlanarDualPair.verticalDualHorizontalEndpoint_false
#print axioms
  PeriodicPlanarDualPair.finiteStripArmArrays_dualCrossingLimits_false
#print axioms PeriodicPlanarDualPair.finiteStripArmArrays_carriedDual_false
#print axioms
  PeriodicPlanarDualPair.finiteStripArmArrays_reframedCarriedDual_false
#print axioms tendsto_max_one_fixedBranch_subsequence
#print axioms
  PeriodicPlaneEmbedding.CommonSquareNormalBoundaryBandData.primalAdjacent_limit_of_pairMerge
#print axioms
  PeriodicPlaneEmbedding.nonempty_carriedCrossNestedArray_of_alignedSharedLevelSteps
