/-
Copyright (c) Meta Platforms, Inc. and affiliates.
All rights reserved.

This source code is licensed under the license found in the
LICENSE file in the root directory of this source tree.
-/

import Code.FK.PeriodicPlanarSheffieldHalfPlaneInfiniteArm

open StatMech.FK.PeriodicPlanar

#print axioms PeriodicGraph.infiniteSetConnectionWithin_measurableSet
#print axioms PeriodicGraph.infiniteSetConnectionWithin_configTranslate
#print axioms PeriodicPlaneEmbedding.unique_two_sides_subset_infiniteBoundaryConnection
#print axioms PeriodicPlaneEmbedding.infiniteBoundaryConnection_measureReal_ge_mul
#print axioms PeriodicPlaneEmbedding.exists_infiniteBoundaryConnection_sequence_tendsto_one
#print axioms PeriodicPlaneEmbedding.shift_down_infiniteLowerBoundaryRay_measureReal_tendsto
#print axioms PeriodicPlaneEmbedding.shift_up_infiniteUpperBoundaryRay_measureReal_tendsto
#print axioms PeriodicPlaneEmbedding.exists_finite_opposite_infiniteBoundaryRays_measureReal_gt
#print axioms exists_adjacent_preference_crossover
#print axioms exists_adjacent_approximate_preference_crossover
#print axioms PeriodicPlaneEmbedding.infiniteLowerBoundaryRay_measureReal_ge_sqrt
#print axioms PeriodicPlaneEmbedding.infiniteUpperBoundaryRay_measureReal_ge_sqrt
#print axioms PeriodicPlaneEmbedding.infiniteLowerBoundaryRay_measureReal_ge_sqrt_sub
#print axioms PeriodicPlaneEmbedding.infiniteUpperBoundaryRay_measureReal_ge_sqrt_sub
#print axioms PeriodicPlaneEmbedding.exists_adjacent_infiniteBoundaryRays_measureReal_ge
#print axioms PeriodicPlaneEmbedding.exists_twoStep_infiniteBoundaryRays_measureReal_ge
#print axioms PeriodicPlaneEmbedding.infiniteBoundaryConnection_measureReal_ge_orbitBox_sq_of_shift
#print axioms PeriodicPlaneEmbedding.infiniteLowerBoundaryRay_measureReal_tendsto_add
#print axioms PeriodicPlaneEmbedding.infiniteUpperBoundaryRay_measureReal_tendsto_sub
#print axioms PeriodicPlaneEmbedding.shift_down_infiniteLowerBoundaryRay_measureReal_tendsto_at
#print axioms PeriodicPlaneEmbedding.shift_up_infiniteUpperBoundaryRay_measureReal_tendsto_at
