/-
Copyright (c) Meta Platforms, Inc. and affiliates.
All rights reserved.

This source code is licensed under the license found in the
LICENSE file in the root directory of this source tree.
-/

import Code.FK.PeriodicPlanarStrictNoCoexistenceClosure

open StatMech.FK.PeriodicPlanar

set_option linter.style.longLine false

#print axioms PeriodicGraph.freeWiredPercolationAgreementOffCountable_of_boundaryCylinders
#print axioms PeriodicGraph.freeWiredBoundaryCylinderAgreementOffCountable_of_increasingCylinders
#print axioms PeriodicGraph.freeWiredPercolationAgreementOffCountable_of_increasingCylinders
#print axioms PeriodicGraph.freeWiredIncreasingCylinderAgreementOffCountable_of_logistic
#print axioms PeriodicPlanarDualPair.freeCommonNoCoexistence_of_commonUniqueNotFull
#print axioms PeriodicPlanarDualPair.strictDualNoCoexistence_of_sheffield_offCountableAgreement
#print axioms PeriodicPlanarDualPair.strictDualNoCoexistence_of_sheffieldNotFull_offCountableAgreement
#print axioms PeriodicPlanarDualPair.strictDualNoCoexistence_of_sheffieldNotFull_increasingCylinders
#print axioms PeriodicPlanarDualPair.strictDualNoCoexistence_of_sheffieldNotFull_logisticCylinders
#print axioms PeriodicPlanarDualPair.dualCritical_relation_of_decay_sheffield_offCountable
#print axioms PeriodicPlanarDualPair.dualCritical_relation_of_decay_sheffieldNotFull_offCountable
#print axioms PeriodicPlanarDualPair.dualCritical_relation_of_decay_sheffieldNotFull_increasingCylinders
#print axioms PeriodicPlanarDualPair.dualCritical_relation_of_decay_sheffieldNotFull_logisticCylinders
