/-
Copyright (c) Meta Platforms, Inc. and affiliates.
All rights reserved.

This source code is licensed under the license found in the
LICENSE file in the root directory of this source tree.
-/

import Code.FK.PeriodicPlanarSheffieldHalfPlaneCage

open StatMech.FK.PeriodicPlanar

#print axioms ContinuousHalfPlaneCrosscut.affinePath
#print axioms ContinuousHalfPlaneCrosscut.horizontalPrefix
#print axioms ContinuousHalfPlaneCrosscut.horizontalPrefix_disjoint_of_range_below
#print axioms ContinuousHalfPlaneCrosscut.horizontalPrefix_disjoint_of_range_above
#print axioms ContinuousHalfPlaneCrosscut.disjoint_of_coord_lt
#print axioms ContinuousHalfPlaneCrosscut.horizontalPrefix_coord_lt
#print axioms ContinuousHalfPlaneCrosscut.rectangleMargin_nonneg_iff
#print axioms ContinuousHalfPlaneCrosscut.exists_first_rectangle_exit_prefix
#print axioms ContinuousHalfPlaneCrosscut.exists_parameter_coord_eq
#print axioms ContinuousHalfPlaneCrosscut.exists_first_parameter_coord_eq
#print axioms ContinuousHalfPlaneCrosscut.exists_last_parameter_coord_eq
#print axioms ContinuousHalfPlaneCrosscut.exists_first_line_contact_suffix
#print axioms ContinuousHalfPlaneCrosscut.exists_last_line_contact_prefix
#print axioms ContinuousHalfPlaneCrosscut.leftCrosscut_intersects_leftRightPath_of_left_between
#print axioms ContinuousHalfPlaneCrosscut.leftCrosscut_intersects_leftTopPath_of_left_between
#print axioms ContinuousHalfPlaneCrosscut.leftCrosscut_intersects_leftBottomPath_of_left_between
#print axioms ContinuousHalfPlaneCrosscut.attachedCrosscut_intersection_reduces_to_core
#print axioms ContinuousHalfPlaneCrosscut.doublyAttached_intersection_reduces_to_cores
#print axioms ContinuousHalfPlaneCrosscut.leftCrosscut_intersects_leftRightPath
#print axioms ContinuousHalfPlaneCrosscut.leftCrosscut_intersects_leftTopPath
#print axioms ContinuousHalfPlaneCrosscut.leftCrosscut_intersects_leftBottomPath
#print axioms PeriodicGraph.exists_open_boundary_walk_of_walk_to_compl
#print axioms PeriodicPlaneEmbedding.infiniteOpenBoundaryConnectionTo_configTranslate_vertical
#print axioms PeriodicPlaneEmbedding.infiniteOpenLowerBoundaryConnection_measureReal_vertical
#print axioms PeriodicPlaneEmbedding.infiniteOpenUpperBoundaryConnection_measureReal_vertical
#print axioms exists_measureReal_pos_of_iUnion_measureReal_pos
#print axioms PeriodicPlaneEmbedding.exists_positive_infiniteOpenLowerBoundaryConnection
#print axioms PeriodicPlaneEmbedding.exists_positive_infiniteOpenUpperBoundaryConnection
#print axioms PeriodicPlaneEmbedding.finiteJoinedBoundaryArmAt_measurableSet
#print axioms PeriodicPlaneEmbedding.finiteJoinedBoundaryArmAt_isIncreasing
#print axioms PeriodicPlaneEmbedding.finiteJoinedBoundaryArmEvent_subset_iUnion_at
#print axioms exists_measureReal_pos_of_countable_iUnion_measureReal_pos
#print axioms PeriodicPlaneEmbedding.exists_positive_finiteJoinedBoundaryArmAt
#print axioms PeriodicPlaneEmbedding.finiteOpenExitedJoinedBoundaryArmEvent_measurableSet
#print axioms PeriodicPlaneEmbedding.finiteOpenExitedJoinedBoundaryArmEvent_isIncreasing
#print axioms measureReal_pos_of_forceOpenFinset_preimage
#print axioms PeriodicPlaneEmbedding.finiteJoinedBoundaryArmAt_forceOpen_subset_exited
#print axioms PeriodicPlaneEmbedding.finiteOpenExitedJoinedBoundaryArmEvent_measureReal_pos
#print axioms PeriodicPlaneEmbedding.exists_positive_finiteOpenExitedJoinedBoundaryArmEvent
#print axioms PeriodicPlaneEmbedding.finiteOpenExitedJoinedBoundaryArmEvent_openWalk
#print axioms PeriodicPlaneEmbedding.rightHalfPlaneBoundaryHasInfiniteCluster_measurableSet
#print axioms PeriodicGraph.clusterWithinSet_infinite_of_connectedWithinSet
#print axioms PeriodicPlaneEmbedding.unique_halfPlane_outside_subset_boundaryInfinite
#print axioms PeriodicPlaneEmbedding.rightHalfPlaneBoundaryHasInfiniteCluster_measure_eq_one
#print axioms PeriodicPlaneEmbedding.rightHalfPlaneBoundaryBandHasInfiniteCluster_measurableSet
#print axioms PeriodicPlaneEmbedding.iUnion_boundaryBandHasInfiniteCluster
#print axioms PeriodicPlaneEmbedding.exists_positive_boundaryBandHasInfiniteCluster
#print axioms PeriodicPlaneEmbedding.simpleWalkArc_coord_lower_of_support
#print axioms PeriodicPlaneEmbedding.simpleWalkArc_coord_upper_of_support
#print axioms PeriodicPlaneEmbedding.exists_boundary_line_attachments
#print axioms PeriodicPlanarDualPair.no_open_dual_escape_of_attached_simpleCrosscut
#print axioms PeriodicPlanarDualPair.no_open_dual_escape_of_doublyAttached_simpleCrosscut
#print axioms PeriodicPlanarDualPair.no_open_dual_escape_of_doublyAttached_subpaths
#print axioms PeriodicPlanarDualPair.complementaryDual_rightHalfPlane_measure_eq_zero_of_orderedJoinedBand_exclusion
#print axioms PeriodicPlanarDualPair.complementaryDual_rightHalfPlane_measure_eq_zero_of_deepJoinedBand_exclusion
#print axioms PeriodicPlanarDualPair.complementaryDual_rightHalfPlane_measure_eq_zero_of_joinedBand_exclusion
#print axioms PeriodicPlaneEmbedding.infiniteOpenBoundaryConnection_measurableSet
#print axioms PeriodicPlaneEmbedding.infiniteOpenBoundaryConnection_isIncreasing
#print axioms PeriodicPlaneEmbedding.unique_two_sides_subset_infiniteOpenBoundaryConnection
#print axioms PeriodicPlaneEmbedding.infiniteOpenBoundaryConnection_measureReal_ge_mul
#print axioms PeriodicPlaneEmbedding.horizontalCrossingEvent_of_openWalk
#print axioms PeriodicPlaneEmbedding.verticalCrossingEvent_of_openWalk
#print axioms PeriodicPlaneEmbedding.exists_open_rectExit_of_clusterWithinSet_infinite
#print axioms PeriodicPlaneEmbedding.exists_open_exposedRectExit_of_rightHalfPlane_cluster
#print axioms PeriodicPlanarDualPair.not_infiniteComplementaryDualClusterWithin_rightHalfPlane_of_threeCrossings
