/-
Copyright (c) Meta Platforms, Inc. and affiliates.
All rights reserved.

This source code is licensed under the license found in the
LICENSE file in the root directory of this source tree.
-/

import Code.Ising.LebowitzPfisterReplicaOrbitRankFiveAggregateFiber

open StatMech.Ising

#print axioms lpReplicaOffdiagDecoratedSource_rank_five_lowRow_rowMask_eq_activeSlots
#print axioms lpReplicaOffdiagDecoratedSource_rank_five_lowRow_inactivePair_mem_eligible
#print axioms lpReplicaOffdiagDecoratedSourceCrossTraceFiberLowRowRankFive_card_le_three
#print axioms lpReplicaOffdiagDecoratedSource_rank_five_highRow_rowMask_eq_univ
#print axioms lpReplicaOffdiagDecoratedSourceCrossTraceFiberHighRowRankFive_card_le_one
#print axioms lpReplicaOffdiagDecoratedSourceCrossTraceFiber_rank_five_eq_low_union_high
#print axioms lpReplicaOffdiagDecoratedSourceCrossTraceFiber_rank_five_card_le_four
