/-
Copyright (c) Meta Platforms, Inc. and affiliates.
All rights reserved.

This source code is licensed under the license found in the
LICENSE file in the root directory of this source tree.
-/

import Code.Ising.LebowitzPfisterReplicaOrbitPairedCutInjection

open StatMech.Ising

#print axioms lpReplicaOrientedFourColorSlotState_ofRowGate
#print axioms lpReplicaOrbitFourColorSlotStateOfTag_cast_profile
#print axioms lpReplicaPartialReflectTransportTag_cast_eq_coupledRaw
#print axioms lpReplicaOrbitFourColorSlotState_partialReflect_of_compatible
#print axioms lpReplicaDecoratedOrbitAtomOfCoupledPairedCut_slotState
#print axioms lpReplicaDecoratedOrbitAtomOfCoupledPairedCutCast_slotState
#print axioms lpReplicaDecoratedOrbitAtomOfRightCoupledPairedCut_slotState
#print axioms lpReplicaDecoratedOrbitAtomOfRightCoupledPairedCutCast_slotState
#print axioms lpReplica_even_card_half_symmDiff_reflect_inter_leftSide
#print axioms LPReplicaEvenLeftBoundary.symmDiff
#print axioms lpReplica_doubledBoundary_evenLeft
#print axioms lpReplica_evenLeft_after_doubledBoundary
#print axioms lpReplica_doubledThenSeam_targetBoundaries
#print axioms lpReplicaBalancedComponentBoundary_ne_seam_symmDiff_ghost
#print axioms lpReplicaRowGate_rightPairedCut_thenSeam
#print axioms LPReplicaRightCoupledPairedCut.half_card_even
#print axioms LPReplicaRightCoupledPairedCut.doubledHalf_ne_seamSource
#print axioms LPReplicaOffdiagCoupledPairedCrossToggleInjection.output_injective
#print axioms lpReplicaOrbitCanonicalFirstTwoSlots_card
#print axioms lpReplicaOrbitCommonSlotOrderKey_injective
#print axioms lpReplicaOrbitCanonicalLastTwoSlots_card
#print axioms lpReplicaOrbitCanonicalLastTwoSlots_terminal
#print axioms lpReplicaOffdiagCoupledPairedCrossToggleInjectionOfFixedMaskRealizations
#print axioms lpReplicaOffdiagCoupledPairedOutputCard_of_crossToggleInjection
#print axioms lpReplicaOffdiagCoupledPairedOutputCard_of_fixedMaskRealizations
#print axioms lpReplicaOffdiagCoupledPairedOutputCard_of_canonicalFirstTwoRealizations
#print axioms lpReplicaOffdiagCoupledPairedOutputCard_of_canonicalLastTwoRealizations
#print axioms lpReplicaOffdiagRightCoupledPairedCut_leftTarget
#print axioms lpReplicaOffdiagRightCoupledPairedCut_rightTarget
#print axioms lpReplicaOffdiagCanonicalLastTwoRightPairedCutRealizable_false
#print axioms lpReplicaOffdiagCanonicalLastTwoRightPairedCutRealizable_target
#print axioms lpReplicaOffdiagDecoratedOrbitInjectionOfFixedMaskTargetRealizations
#print axioms lpReplicaOffdiagOrbitAtomCardInequality_of_canonicalLastTwoRightPairedCuts
#print axioms lpReplicaOffdiagCoupledPairedHall_of_crossToggleInjection
#print axioms lpReplicaOffdiagOrbitAtomCardInequality_of_coupledPairedCrossToggleInjection
