/-
Copyright (c) Meta Platforms, Inc. and affiliates.
All rights reserved.

This source code is licensed under the license found in the
LICENSE file in the root directory of this source tree.
-/

import Code.FrontierD.SixVertexDisagreementComponentCType

open StatMech.FrontierD

#print axioms sixVertexTorusSwitchFirst_involutive
#print axioms sixVertexTorusSwitchSecond_involutive
#print axioms sixVertexLexDisagreementComponentSwitch_local_eq_or_swap
#print axioms sixVertexLexDisagreementComponentSwitch_totalCTypeCount
#print axioms sixVertexLexDisagreementComponentSwitch_multiplicityNat
#print axioms sixVertexLexDisagreementComponentSwitch_markedWeight
#print axioms intCast_upCount_switchFirst_eq_add_seamTransfer
#print axioms intCast_upCount_switchSecond_eq_sub_seamTransfer
#print axioms two_le_card_sixVertexPositiveSeamDisagreements
#print axioms exists_two_positiveSeamDisagreements
#print axioms sixVertexTorusSwitchFirst_fullDisagreement
#print axioms sixVertexFullDisagreementMask_seamTransfer_eq_two
#print axioms sixVertexLexDisagreementComponentSwitch_to_middle_of_transfer_one
