/-
Copyright (c) Meta Platforms, Inc. and affiliates.
All rights reserved.

This source code is licensed under the license found in the
LICENSE file in the root directory of this source tree.
-/

import Code.FrontierD.SixVertexDegreeTwoAlignedSlotColorInvariant

open StatMech.FrontierD

#print axioms sixVertexDegreeTwoBranchClosedUnitPrefix_branchSwap_mem_iff
#print axioms sixVertexDegreeTwoBranchClosedUnitPrefix_charge
#print axioms sixVertexDegreeTwoBranchClosedBoundaryFinKey_injective
#print axioms sixVertexDegreeTwoBranchClosedBoundaryFinKey_exists_iff
#print axioms sixVertexDegreeTwoBranchClosedOccurrenceSlotEquiv_apply_dart
#print axioms sixVertexDegreeTwoBranchClosedBoundarySegments_branchSwap_mem_iff
#print axioms sixVertexDegreeTwoBranchClosedSelected_branchSwap
#print axioms sixVertexDegreeTwoBranchClosedExpandedTargetPairing_recover
#print axioms sixVertexDegreeTwoBranchClosedExpandedTargetBoundary
#print axioms fkMedialBlackBoundaryPerm_togglePairingMask
#print axioms fkColoredBlackDartStrandSlotEquiv_togglePairingMask
#print axioms fkColoredStrandSlotBoundaryPerm_togglePairingMask
#print axioms sixVertexDegreeTwoBranchClosedExpandedTargetPairing_inactive
#print axioms sixVertexDegreeTwoBranchClosedExpandedTargetPairing_active
#print axioms sixVertexDegreeTwoBranchClosedTransportedColor_dart
#print axioms sixVertexDegreeTwoBranchClosedTransportedColor_dart_of_inactive
#print axioms sixVertexDegreeTwoAlignedSourceBoundary_slotOfFalseDart
#print axioms sixVertexDegreeTwoAlignedTrueFirstReturn_arrival
#print axioms sixVertexDegreeTwoBranchClosedSelected_trueFirstReturn
#print axioms fkColoredParityMaskStrandSlotSwap_slotOfFalseDart
#print axioms sixVertexDegreeTwoBranchClosedExpandedTargetBoundary_slotOfFalseDart
#print axioms fkColoredStrandSlotBoundaryPerm_retie_apply_of_away
#print axioms sixVertexDegreeTwoAlignedTargetBoundary_apply_of_away
#print axioms sixVertexDegreeTwoAlignedTransportedColor_dart
#print axioms sixVertexDegreeTwoAlignedTransportedColor_dart_of_inactive
#print axioms sixVertexDegreeTwoAlignedColoredSource_falseBoundary_color
#print axioms sixVertexDegreeTwoAlignedTransportedColor_falseBoundary_of_inactive
#print axioms doubledAlignedBoundarySegments_step_mem_iff_of_state_invariant
