/-
Copyright (c) Meta Platforms, Inc. and affiliates.
All rights reserved.

This source code is licensed under the license found in the
LICENSE file in the root directory of this source tree.
-/

import Code.FrontierD.SixVertexAlignedFirstReturn

open StatMech.FrontierD

#print axioms alignedRoutingPairing_compatible
#print axioms boundaryAlignedSlotColor_bne
#print axioms boundaryAlignedComplementSlotColor_bne
#print axioms boundaryAlignedSlotQRaw_complement_color_bne_of_pairing_ne
#print axioms doubledAlignedSlotEmbedding
#print axioms alignedFirstReturnTime_eq
#print axioms mem_doubledAlignedBoundarySegments_step_iff_of_inactive_arrival
#print axioms mem_doubledAlignedBoundarySegments_predecessor_iff
#print axioms doubledAlignedBoundarySegments_eq_map_layerSwap
#print axioms doubledAlignedFirstReturnPerm
#print axioms sum_doubledAlignedCharge_eq_two
#print axioms canonicalDoubledAlignedSelectedStates_nodup
#print axioms CanonicalDoubledAlignedOrbitChunkCut.cutLeft_mem_selected
#print axioms CanonicalDoubledAlignedOrbitChunkCut.cutRight_not_mem_selected
#print axioms CanonicalDoubledAlignedOrbitChunkCut.selected_predecessor_iff_of_ne_heads
#print axioms CanonicalDoubledAlignedOrbitChunkCut.rightHead_transition
#print axioms CanonicalDoubledAlignedOrbitChunkCut.leftHead_transition
#print axioms canonicalDoubledAlignedOrbitChunkCut_cases
#print axioms alignedPermOrderedAllOrbitLists_prefix_mem_iff
#print axioms CanonicalDoubledAlignedOrbitChunkCut.selected_invariant_of_left_empty
#print axioms CanonicalDoubledAlignedOrbitChunkCut.selected_invariant_of_right_empty
#print axioms doubledAlignedBranchSwap
#print axioms doubledAlignedSlot_branchSwap
#print axioms doubledAlignedState_eq_or_branchSwap_of_vertex_eq
#print axioms alignedBoundaryPerm_false_eq_true_layerSwap
#print axioms alignedPermOrderedAllOrbitLists_sameCycle_of_mem
