/-
Copyright (c) Meta Platforms, Inc. and affiliates.
All rights reserved.

This source code is licensed under the license found in the
LICENSE file in the root directory of this source tree.
-/

import Code.FrontierD.SixVertexConfigurationPairedBranchHall

open StatMech.FrontierD

#print axioms SixVertexConfigurationPairedBranchGeometricConstruction.toEmbeddings
#print axioms SixVertexConfigurationPairedBranchEmbeddings.source_degree
#print axioms SixVertexConfigurationPairedBranchEmbeddings.inverseCode
#print axioms SixVertexConfigurationPairedBranchEmbeddings.inverse_degree
#print axioms SixVertexConfigurationPairedBranchEmbeddings.hall
#print axioms sixVertexConfigurationPairedBranchConstructionOfIsEmpty
#print axioms configurationPairedBranchConstructions_of_nonempty_sources
#print axioms configurationBigradeFibers_of_pairedBranchConstructions
#print axioms sixVertexMarkedTraceCoefficientwiseLogConcave_of_configurationPairedBranches
#print axioms sixVertexSectorTrace_logConcave_of_configurationPairedBranches
