/-
Copyright (c) Meta Platforms, Inc. and affiliates.
All rights reserved.

This source code is licensed under the license found in the
LICENSE file in the root directory of this source tree.
-/

import Code.FrontierD.SixVertexDegreeTwoSynchronizedUnitPhysicalKey

namespace StatMech.FrontierD

#print axioms finitePerm_function_invariant_of_firstReturn
#print axioms finitePerm_function_invariant_of_firstReturn_of_inactive_arrival
#print axioms sixVertexDegreeTwoSynchronizedComponentTransitionVertex_eq_branch
#print axioms sixVertexDegreeTwoSynchronizedComponentPhysicalRetieMask_active
#print axioms sixVertexDegreeTwoSynchronizedComponentPhysicalRetieMask_inactive
#print axioms sixVertexDegreeTwoSynchronizedComponentPhysicalTargetPairing_active
#print axioms sixVertexDegreeTwoSynchronizedComponentPhysicalTargetPairing_inactive
#print axioms sixVertexDegreeTwoSynchronizedComponentPhysicalTargetPairing_recover
#print axioms sixVertexDegreeTwoSynchronizedComponentPhysicalTargetBoundary
#print axioms sixVertexDegreeTwoSynchronizedComponentPhysicalFirstReturn_active
#print axioms sixVertexDegreeTwoSynchronizedComponentDoubledSelector_returnState_bne
#print axioms sixVertexDegreeTwoSynchronizedComponentPhysicalFirstReturn_slot
#print axioms sixVertexDegreeTwoSynchronizedComponentPhysicalSourceReturnState_color
#print axioms sixVertexDegreeTwoSynchronizedComponent_mem_states_iff
#print axioms sixVertexDegreeTwoSynchronizedComponent_states_nodup
#print axioms sixVertexDegreeTwoSynchronizedComponent_branchSwap_mem_states_iff
#print axioms sixVertexDegreeTwoSynchronizedComponentBoundaryFinKey_injective
#print axioms sixVertexDegreeTwoSynchronizedComponentOccurrenceEquiv_self
#print axioms sixVertexDegreeTwoSynchronizedComponentBoundaryFinKey_exists_iff
#print axioms sixVertexDegreeTwoSynchronizedComponentOccurrenceEquiv_apply
#print axioms sixVertexDegreeTwoSynchronizedComponentOccurrenceEquiv_apply_of_not_mem
#print axioms sixVertexDegreeTwoSynchronizedComponentTransportedColor_dart
#print axioms sixVertexDegreeTwoSynchronizedComponentTransportedColor_dart_of_inactive
#print axioms sixVertexDegreeTwoSynchronizedComponentTransportedColor_falseBoundary_of_inactive
#print axioms sixVertexDegreeTwoSynchronizedComponentBoundaryFalseDart_of_inactive
#print axioms sixVertexDegreeTwoSynchronizedComponentTargetBoundary_slotOfFalseDart
#print axioms sixVertexDegreeTwoSynchronizedComponentSlotColorInvariant_of_falseDart
#print axioms sixVertexDegreeTwoSynchronizedComponentSlotColorInvariant_of_active
#print axioms sixVertexDegreeTwoSynchronizedComponentSpliceOfActive
#print axioms sixVertexDegreeTwoSynchronizedComponentTransportedActiveColor_eq
#print axioms sixVertexDegreeTwoSynchronizedComponentTransportedColor_firstReturn

end StatMech.FrontierD
