/-
Copyright (c) Meta Platforms, Inc. and affiliates.
All rights reserved.

This source code is licensed under the license found in the
LICENSE file in the root directory of this source tree.
-/

import Code.FrontierD.SixVertexBetheSymmetricStabilityComponent
import Code.FrontierD.SixVertexBetheOddSymmetricAnalytic
import Code.FrontierD.SixVertexBetheSymmetricDominance

#print axioms StatMech.FrontierD.sixVertexEvenSymmetricLift_symmetric
#print axioms StatMech.FrontierD.sixVertexBetheResidual_symmetric
#print axioms StatMech.FrontierD.sixVertexEvenSymmetricBetheResidual_eq_zero_iff
#print axioms StatMech.FrontierD.exists_sixVertexLocalAnalyticEvenSymmetricBetheBranch
#print axioms StatMech.FrontierD.sixVertexEvenSymmetricBetheRootJacobian_toMatrix'_apply
#print axioms StatMech.FrontierD.sixVertexEvenSymmetricBetheRootJacobian_injective_of_diagonalDominance
#print axioms StatMech.FrontierD.sixVertexBethePositiveHalfJacobianMatrix_offdiag_nonneg
#print axioms StatMech.FrontierD.sixVertexPositiveHalfRootGap_pos_of_open
#print axioms StatMech.FrontierD.sixVertexBethePositiveHalfScaledJacobianMatrix_diag
#print axioms StatMech.FrontierD.sixVertexEvenSymmetricBetheRootJacobian_injective_of_scaledDiagonalDominance
#print axioms StatMech.FrontierD.isLocalHomeomorphOn_sixVertexBetheContinuationProjection_of_evenSymmetricJacobian
#print axioms StatMech.FrontierD.exists_sixVertexContinuousEvenSymmetricBetheBranch_of_jacobian
#print axioms StatMech.FrontierD.exists_sixVertexContinuousEvenSymmetricBetheBranch_of_stabilityGauge
#print axioms StatMech.FrontierD.sixVertexOddSymmetricBetheResidual_eq_zero_iff
#print axioms StatMech.FrontierD.exists_sixVertexLocalAnalyticOddSymmetricBetheBranch
#print axioms StatMech.FrontierD.sixVertexEvenSymmetricBetheRootJacobian_injective_of_sourceBounds
