/-
Copyright (c) Meta Platforms, Inc. and affiliates.
All rights reserved.

This source code is licensed under the license found in the
LICENSE file in the root directory of this source tree.
-/

import Code.Universality.IsingFermionicStripCauchyFourthOrder

#print axioms isingFermionic_verticalOscillation_cauchy_fourth
#print axioms isingFermionic_strip_cauchy_fourth
#print axioms isingFermionic_norm_iteratedFDeriv_real_im_le_iteratedDeriv
#print axioms isingFermionic_verticalOscillation_im_fourth_tensor
#print axioms isingFermionic_strip_im_fourth_tensor
#print axioms isingFermionic_verticalOscillation_im_fourthTensor_le_on_halfBall
#print axioms isingFermionic_unitStrip_im_fourthTensor_le_on_halfBall

namespace StatMech.Universality
namespace FKIsingSquareBoundaryLayerCoordinateOneForm

#print axioms LocalDiagonalFourthOrderAnalyticData.ofUnitStripOnBall
#print axioms LocalDiagonalFourthOrderAnalyticData.ofVerticalOscillationOnBall
#print axioms unitStripCenteredBallFourthOrderResidualBound_eq
#print axioms unitStripCenteredBallFourthOrderResidualBound_distanceScale
#print axioms verticalOscillationCenteredBallFourthOrderResidualBound_eq
#print axioms verticalOscillationCenteredBallFourthOrderResidualBound_distanceScale
#print axioms LocalDiagonalFourthOrderAnalyticData.ofUnitStripOnCenteredBall
#print axioms LocalDiagonalFourthOrderAnalyticData.ofVerticalOscillationOnCenteredBall
#print axioms fullSquareScaledVertex_sampledLaplacian_le_unitStripCenteredBall
#print axioms fullSquareScaledFace_sampledLaplacian_le_unitStripCenteredBall
#print axioms fullSquareScaledVertex_sampledLaplacian_le_verticalOscillationCenteredBall
#print axioms fullSquareScaledFace_sampledLaplacian_le_verticalOscillationCenteredBall
#print axioms fullSquareScaledVertex_sampledLaplacian_le_endpointRadiusQuartic
#print axioms fullSquareScaledFace_sampledLaplacian_le_endpointRadiusQuartic
#print axioms
  fullSquareScaledVertex_sampledLaplacian_le_endpointRadiusQuartic_of_verticalOscillation
#print axioms
  fullSquareScaledFace_sampledLaplacian_le_endpointRadiusQuartic_of_verticalOscillation
#print axioms vertexSpatialTargetResidual_sampled_eq_graphLaplacian_of_bulk
#print axioms faceSpatialTargetResidual_sampled_eq_graphLaplacian_of_bulk
#print axioms vertexSpatialTargetResidual_sampled_le_endpointRadiusQuartic_of_bulk
#print axioms faceSpatialTargetResidual_sampled_le_endpointRadiusQuartic_of_bulk
#print axioms
  vertexSpatialTargetResidual_sampled_le_endpointRadiusQuartic_of_bulk_verticalOscillation
#print axioms
  faceSpatialTargetResidual_sampled_le_endpointRadiusQuartic_of_bulk_verticalOscillation
#print axioms vertexSpatialTargetResidual_sampled_le_endpointRadiusQuartic
#print axioms faceSpatialTargetResidual_sampled_le_endpointRadiusQuartic
#print axioms PhysicalEndpointVariableFourthOrderBulkData.ofUnitStripCenteredBalls

end FKIsingSquareBoundaryLayerCoordinateOneForm

end StatMech.Universality
