/-
Copyright (c) Meta Platforms, Inc. and affiliates.
All rights reserved.

This source code is licensed under the license found in the
LICENSE file in the root directory of this source tree.
-/

import Code.Universality.IsingFermionicPhysicalFullSquareBoundaryLayerDirichletRate

set_option linter.style.longLine false

#print axioms
  StatMech.Universality.FKIsingSquareBoundaryLayerCoordinateOneForm.fullSquareScaledCoordinateEmbedding_unitAxial_dist
#print axioms
  StatMech.Universality.FKIsingSquareBoundaryLayerCoordinateOneForm.FullSquareCoordinateEmbeddingCompatibility.incidenceDistance
#print axioms
  StatMech.Universality.FKIsingSquareBoundaryLayerCoordinateOneForm.fullSquareScaledEmbedding_incidenceDistance
#print axioms
  StatMech.Universality.FKIsingSquareBoundaryLayerCoordinateOneForm.fullSquareScaledVertex_sampledLaplacian_eq_stencil
#print axioms
  StatMech.Universality.FKIsingSquareBoundaryLayerCoordinateOneForm.fullSquareScaledFace_sampledLaplacian_eq_stencil
#print axioms
  StatMech.Universality.FKIsingSquareBoundaryLayerCoordinateOneForm.fullSquareScaledVertex_sampledLaplacian_le_fourthOrder
#print axioms
  StatMech.Universality.FKIsingSquareBoundaryLayerCoordinateOneForm.fullSquareScaledFace_sampledLaplacian_le_fourthOrder
#print axioms
  StatMech.Universality.FKIsingSquareBoundaryLayerCoordinateOneForm.vertexSampled_boundaryConsistencyError_le
#print axioms
  StatMech.Universality.FKIsingSquareBoundaryLayerCoordinateOneForm.faceSampled_boundaryConsistencyError_le
#print axioms
  StatMech.Universality.FKIsingSquareBoundaryLayerCoordinateOneForm.vertexSampled_boundaryConsistencyError_eq_zero
#print axioms
  StatMech.Universality.FKIsingSquareBoundaryLayerCoordinateOneForm.faceSampled_boundaryConsistencyError_eq_zero
#print axioms
  StatMech.Universality.FKIsingSquareBoundaryLayerCoordinateOneForm.vertexSampled_targetResidual_le
#print axioms
  StatMech.Universality.FKIsingSquareBoundaryLayerCoordinateOneForm.faceSampled_targetResidual_le
#print axioms
  StatMech.Universality.FKIsingSquareBoundaryLayerCoordinateOneForm.vertexSampled_targetResidual_le_of_laplacian_and_trace
#print axioms
  StatMech.Universality.FKIsingSquareBoundaryLayerCoordinateOneForm.faceSampled_targetResidual_le_of_laplacian_and_trace
#print axioms
  StatMech.Universality.FKIsingSquareBoundaryLayerCoordinateOneForm.vertexSampled_targetResidual_le_of_exact_free_trace
#print axioms
  StatMech.Universality.FKIsingSquareBoundaryLayerCoordinateOneForm.faceSampled_targetResidual_le_of_exact_free_trace
#print axioms
  StatMech.Universality.FKIsingSquareBoundaryLayerCoordinateOneForm.vertexExplicitPoissonBarrier_laplacian
#print axioms
  StatMech.Universality.FKIsingSquareBoundaryLayerCoordinateOneForm.vertexPoissonBarrierBound_le_growth
#print axioms
  StatMech.Universality.FKIsingSquareBoundaryLayerCoordinateOneForm.faceRowPoissonBarrier_laplacian
#print axioms
  StatMech.Universality.FKIsingSquareBoundaryLayerCoordinateOneForm.facePoissonBarrierBound_le_growth
#print axioms
  StatMech.Universality.FKIsingSquareBoundaryLayerCoordinateOneForm.sampledWeightedConsistency_tendsto_of_quadraticRates
#print axioms
  StatMech.Universality.FKIsingSquareBoundaryLayerCoordinateOneForm.sampledWeightedConsistency_tendsto_of_meshAndQuadraticResidual
#print axioms
  StatMech.Universality.FKIsingSquareBoundaryLayerCoordinateOneForm.physicalIncidence_sampledTarget_error_le
#print axioms
  StatMech.Universality.FKIsingSquareBoundaryLayerCoordinateOneForm.physicalIncidence_uniform_convergence_of_sampledConsistency
#print axioms
  StatMech.Universality.FKIsingSquareBoundaryLayerCoordinateOneForm.physicalIncidence_uniform_convergence_of_lipschitzSamples
#print axioms
  StatMech.Universality.FKIsingSquareBoundaryLayerCoordinateOneForm.physicalIncidence_uniform_convergence_of_meshAndQuadraticResidual
#print axioms
  StatMech.Universality.FKIsingSquareBoundaryLayerCoordinateOneForm.physicalIncidence_uniform_convergence_of_scaledMeshAndQuadraticResidual
#print axioms
  StatMech.Universality.FKIsingSquareBoundaryLayerCoordinateOneForm.physicalIncidence_uniform_convergence_of_scaledExactBoundaryAndLaplacian
