/-
Copyright (c) Meta Platforms, Inc. and affiliates.
All rights reserved.

This source code is licensed under the license found in the
LICENSE file in the root directory of this source tree.
-/

import Code.Universality.IsingFermionicSquareWiredSwitching

namespace StatMech.Universality

#print axioms fkIsingSquareWiredBoundaryDart_endpoint_mem_wiredArc
#print axioms fkIsingSquareWiredBondMate_primalLabel_reachable
#print axioms fkIsingSquareWiredLoopGraph_adj_primalLabel_reachable
#print axioms fkIsingSquareWiredLoopGraph_reachable_primalLabel_reachable
#print axioms fkIsingSquareWired_double_visit_closed_endpoints_reachable
#print axioms fkIsingSquareWiredCompletedLoopGraph_reachable_iff
#print axioms fkIsingSquareWired_one_visit_completedLoop_componentCount
#print axioms fkIsingSquareWired_double_visit_clusterCount_eq
#print axioms fkIsingSquareWired_double_visit_criticalMass_open_eq_sqrtTwo_mul_closed
#print axioms fkIsingSquareWired_one_visit_separated_of_eulerDefect_eq

end StatMech.Universality
