/-
Copyright (c) Meta Platforms, Inc. and affiliates.
All rights reserved.

This source code is licensed under the license found in the
LICENSE file in the root directory of this source tree.
-/

import Code.Universality.IsingFermionicSquareWiredExhaustive

namespace StatMech.Universality

#print axioms fkIsingSquareWired_closed_west_south_phase
#print axioms fkIsingSquareWired_closed_east_north_phase
#print axioms fkIsingSquareWired_open_west_north_phase
#print axioms fkIsingSquareWired_open_east_south_phase
#print axioms fkIsingSquareWired_no_visit_pointwise_contour_balance
#print axioms fkIsingSquareWired_one_visit_west_pointwise_contour_balance
#print axioms fkIsingSquareWired_one_visit_east_pointwise_contour_balance
#print axioms fkIsingSquareWiredExhaustiveBondMate_primalLabel_reachable
#print axioms fkIsingSquareWiredExhaustiveLoopGraph_reachable_primalLabel_reachable
#print axioms fkIsingSquareWiredExhaustive_double_visit_closed_endpoints_reachable
#print axioms fkIsingSquareWiredExhaustive_double_visit_clusterCount_eq
#print axioms fkIsingSquareWiredExhaustive_double_visit_criticalMass_open_eq_sqrtTwo_mul_closed

end StatMech.Universality
