/-
Copyright (c) Meta Platforms, Inc. and affiliates.
All rights reserved.

This source code is licensed under the license found in the
LICENSE file in the root directory of this source tree.
-/

import Code.Universality.IsingFermionicDirichletComparison

open StatMech.Universality

#print axioms isingFiniteGraph_laplacian_comparison
#print axioms isingFiniteGraph_subharmonic_le_harmonic
#print axioms isingFiniteGraph_harmonic_le_superharmonic
#print axioms isingFiniteGraphLaplacian_add_const
#print axioms isingFiniteGraphLaplacian_add
#print axioms isingFiniteGraphLaplacian_const_mul
#print axioms isingFiniteGraph_harmonic_boundary_stability
#print axioms isingFiniteGraphDirichletOperator_injective
#print axioms isingFiniteGraph_exists_harmonic_extension
#print axioms isingFiniteGraphDirichletOperator_solve
#print axioms isingFiniteGraphPoissonBarrier_boundary
#print axioms isingFiniteGraphPoissonBarrier_laplacian
#print axioms isingFiniteGraphPoissonBarrier_nonneg
#print axioms isingFiniteGraphPoissonBarrier_le_bound
#print axioms isingFiniteGraph_subsuperharmonic_boundary_stability
#print axioms isingFiniteGraph_harmonic_approximation_of_barrier
#print axioms isingFiniteGraph_harmonic_approximation_of_residual
