/-
Copyright (c) Meta Platforms, Inc. and affiliates.
All rights reserved.

This source code is licensed under the license found in the
LICENSE file in the root directory of this source tree.
-/

import Code.Universality.IsingFermionicDenseIncidencePrimitiveBridge

open Filter Set Topology

#print axioms StatMech.Universality.FKIsingDenseIncidencePrimitivePathCompatibility.tendsto_canonical_sub_discrete
#print axioms StatMech.Universality.FKIsingDenseIncidencePrimitivePathCompatibility.canonicalPrimitive_tendsto
#print axioms StatMech.Universality.isingFermionicEntireSquarePrimitive_tendsto_at_of_continuous
#print axioms StatMech.Universality.isingFermionicEntireSquarePrimitive_values_do_not_force_root
#print axioms StatMech.Universality.FKIsingCaratheodoryApproximation.StableFullMedialInterpolation.scalingLimit_of_compactHolder_denseIncidencePaths
#print axioms StatMech.Universality.FKIsingCaratheodoryApproximation.BoundaryRadialTensorTentGeometry.scalingLimit_of_compactHolder_denseIncidencePaths
