/-
Copyright (c) Meta Platforms, Inc. and affiliates.
All rights reserved.

This source code is licensed under the license found in the
LICENSE file in the root directory of this source tree.
-/

import Code.Universality.IsingFermionicPhysicalFullSquareBoundaryLayerDirichletResidual

set_option linter.style.longLine false

#print axioms StatMech.Universality.isingFiniteWeightedLaplacian_add_const
#print axioms StatMech.Universality.isingFiniteWeightedDirichletOperator_solve
#print axioms StatMech.Universality.isingFiniteWeightedPoissonBarrier_boundary
#print axioms StatMech.Universality.isingFiniteWeightedPoissonBarrier_laplacian
#print axioms StatMech.Universality.isingFiniteWeightedPoissonBarrier_nonneg
#print axioms StatMech.Universality.isingFiniteWeightedPoissonBarrier_le_bound
#print axioms
  StatMech.Universality.isingFiniteWeighted_harmonic_approximation_of_barrier
#print axioms
  StatMech.Universality.isingFiniteWeighted_harmonic_approximation_of_residual
#print axioms StatMech.Universality.isingFiniteWeightedBoundaryError_nonneg
#print axioms StatMech.Universality.isingFiniteWeightedBoundaryError_bound
#print axioms StatMech.Universality.isingFiniteWeightedTargetResidual_nonneg
#print axioms StatMech.Universality.isingFiniteWeightedTargetResidual_bound
#print axioms
  StatMech.Universality.FKIsingSquareBoundaryLayerCoordinateOneForm.vertexBoundaryConsistencyError_fixed_bound
#print axioms
  StatMech.Universality.FKIsingSquareBoundaryLayerCoordinateOneForm.vertexBoundaryConsistencyError_ghost_bound
#print axioms
  StatMech.Universality.FKIsingSquareBoundaryLayerCoordinateOneForm.faceBoundaryConsistencyError_fixed_bound
#print axioms
  StatMech.Universality.FKIsingSquareBoundaryLayerCoordinateOneForm.faceBoundaryConsistencyError_ghost_bound
#print axioms
  StatMech.Universality.FKIsingSquareBoundaryLayerCoordinateOneForm.vertexTargetResidual_robin_bound
#print axioms
  StatMech.Universality.FKIsingSquareBoundaryLayerCoordinateOneForm.faceTargetResidual_robin_bound
#print axioms
  StatMech.Universality.FKIsingSquareBoundaryLayerCoordinateOneForm.vertexDirichlet_target_error_le
#print axioms
  StatMech.Universality.FKIsingSquareBoundaryLayerCoordinateOneForm.faceDirichlet_target_error_le
#print axioms
  StatMech.Universality.FKIsingSquareBoundaryLayerCoordinateOneForm.physicalIncidence_target_error_le
#print axioms
  StatMech.Universality.FKIsingSquareBoundaryLayerCoordinateOneForm.physicalIncidence_uniform_convergence_of_weightedConsistency
