/-
Copyright (c) Meta Platforms, Inc. and affiliates.
All rights reserved.

This source code is licensed under the license found in the
LICENSE file in the root directory of this source tree.
-/

import Code.Universality.IsingFermionicCenteredTensorTentRegularity

open StatMech.Universality

#print axioms lipschitzOnWith_of_open_local_on_convex
#print axioms complexBilinearCell_right_eq_left
#print axioms complexBilinearCell_top_eq_bottom
#print axioms complexBilinearCell_horizontalAdjacent_norm_sub_le
#print axioms complexBilinearCell_verticalAdjacent_norm_sub_le
#print axioms complexBilinearHorizontalStrip_norm_sub_le
#print axioms complexBilinearVerticalStrip_norm_sub_le
#print axioms complexBilinearTwoByTwo_norm_sub_le
#print axioms finiteCenteredRadialGridInterpolant_horizontalBoundary
#print axioms finiteCenteredRadialGridInterpolant_verticalBoundary
#print axioms isingCenteredRadialGridCellPoint_add_one_x
#print axioms isingCenteredRadialGridCellPoint_add_one_y
#print axioms finiteCenteredRadialGridInterpolant_twoByTwo
#print axioms finiteCenteredRadialGridInterpolant_twoByTwo_norm_sub_le_dist
#print axioms finiteCenteredRadialGridInterpolant_horizontalAdjacent_norm_sub_le
#print axioms finiteCenteredRadialGridInterpolant_verticalAdjacent_norm_sub_le
#print axioms finiteCenteredRadialGridInterpolant_horizontalAdjacent_norm_sub_le_dist
#print axioms finiteCenteredRadialGridInterpolant_verticalAdjacent_norm_sub_le_dist
#print axioms fkIsingExpandingBoundarySquareCenteredReflectedInterpolant_horizontalAdjacent_norm_sub_le_of_neighbor
#print axioms fkIsingExpandingBoundarySquareCenteredReflectedInterpolant_verticalAdjacent_norm_sub_le_of_neighbor
#print axioms fkIsingSquareBoundaryCenteredRadialPatch_normalizedNeighbor_norm_sub_le_of_radialWindow
#print axioms isingCenteredRadialGridCoordinate_cellPoint
#print axioms isingCenteredRadialGridCellPoint_coordinate
#print axioms exists_twoByTwo_cell_of_centeredCoordinate
#print axioms closedBall_subset_finiteCenteredRadialGridStrictInterior
#print axioms finiteCenteredRadialGridDeeperInterior
#print axioms closedBall_subset_finiteCenteredRadialGridDeeperInterior
#print axioms finiteCenteredRadialGridInterpolant_lipschitzOnWith_of_neighbor
#print axioms finiteCenteredRadialGridInterpolant_lipschitzOnWith_of_strictNeighbor
#print axioms isingLinearTent_lipschitzWith
#print axioms finiteRadialGridInterpolant_locallyLipschitz
#print axioms finiteCenteredRadialGridInterpolant_locallyLipschitz
#print axioms fkIsingExpandingBoundarySquareCenteredReflectedInterpolant_locallyLipschitz
#print axioms exists_lipschitzOnWith_forall_lt_of_locallyLipschitz
#print axioms fkIsingExpandingBoundarySquareCenteredReflectedInterpolant_lipschitzOnWith_closedBall_of_neighbor
#print axioms fkIsingExpandingBoundarySquareCenteredReflectedInterpolant_lipschitzOnWith_closedBall_of_strictNeighbor
#print axioms FKIsingExpandingCenteredNeighborTransport
#print axioms FKIsingExpandingCenteredStrictNeighborTransport
#print axioms fkIsingExpandingBoundarySquareCenteredReflectedInterpolant_meshUniformCompactHolder_of_centeredNeighbor
#print axioms fkIsingExpandingBoundarySquareCenteredReflectedInterpolant_meshUniformCompactHolder_of_centeredStrictNeighbor
#print axioms fkIsingSquareCenteredRadialPatchEdge_add_side_eq_radialPatchEdge
#print axioms fkIsingSquareBoundaryCenteredRadialPatchFullObservable_add_side_eq_radialPatch
#print axioms fkIsingSquareBoundaryCenteredRadialPatchFullObservable_add_side_eq_window
#print axioms fkIsingSquareBoundaryCenteredRadialPatch_add_side_normalizedNeighbor_norm_sub_le
#print axioms fkIsingSquareBoundaryCenteredRadialPatch_add_side_cell_edges_halfScale
#print axioms isingCenteredRadialIndexSector
#print axioms fkIsingExpandingCenteredNeighborTransport_of_four_sector_bounds
